name = "NeuronBifurcate"
uuid = "d7b4198e-a23e-4c33-9bf5-e25a08b66186"
authors = ["Robert Gowers"]
version = "0.1.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Parameters = "0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
